# Generated by Django 5.2.3 on 2025-09-18 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
