# Generated by Django 5.2.3 on 2025-09-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0003_alter_expenses_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
