# Generated by Django 5.2.6 on 2025-10-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0004_alter_expenses_created_at_alter_expenses_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(choices=[('Comida', 'Comida'), ('Transporte', 'Transporte'), ('Entretenimiento', 'Entretenimiento'), ('Salud', 'Salud'), ('Otro', 'Otro')], max_length=20),
        ),
    ]
